typography_spectrum: 0.5119509131181985
color:
  brandStrength: 0.6123680693563074
  lightness: 0.09482890483923256
  saturation: 0.7390921865589917
  rhythmicContrast: 0.8181733002420515
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
layout_spectrum: 0.7144998812582344
author:
  name: Sherry Hamilton
  email: eptworks2@gmail.com
  url: www.eptworkshuntsville.com
name: EPT Emotional Healthcare
title: EPT Therapy is a Certified Specialty Profession in Emotional Healthcare.
description: Forgiveness with Significance Every Session
